#!/usr/bin/env bash
#installation of nginx on remote server
ssh ubuntu@54.197.131.36 "sudo apt -y install nginx"
echo "Hello World!" > /var/www/html/index.html
ssh ubuntu@54.197.131.36 "sudo /etc/init.d/nginx restart"
