#!/usr/bin/env bash
#installation of nginx on remote server
sudo apt update
sudo apt -y install nginx
sudo sh -c 'echo "Hello World!" | tee /var/www/html/index.html'
sudo sh -c "echo 'server {
    listen 80;
    server_name localhost;
    location / {
        root /var/www/html;
        index index.html;
    }

}' >> /etc/nginx/sites-enabled/default"
sudo service nginx restart

