#!/usr/bin/env bash
#installation of nginx on remote server
sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" | tee /var/www/html/index.html'
sh -c "echo 'server {
    listen 80;

}' | sudo tee /etc/nginx/sites-enabled/default" > /dev/null
sudo service nginx restart