#!/usr/bin/env bash
#redirection with 301 status code
nginxserver="server{
    location /redirect_me{
        return 301 http://54.197.131.36;
    }
}"
ssh ubuntu@54.197.131.36 "echo '$nginxserver' | sudo tee /etc/nginx/sites-enabled/default"
