#!/usr/bin/env bash
#redirection with 404 status code

sudo apt update
sudo apt -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sh -c "echo 'server {
    listen 80;
    server_name 54.197.131.36;
    location / {
        root /var/www/html;
        index index.html;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /400.html;
    location = /400.html {
        root /var/www/html;
        internal;
    }

}' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
