#!/usr/bin/env bash
#install and configure a load balancer(HAproxy) on server
studentid=415786

sudo apt update
sudo apt install -y haproxy
echo -e "frontend serverfront *:80\n\
    default_backend serverback" | sudo tee -a /etc/haproxy/haproxy.cfg

echo -e "backend serverback\n\
    balance roundrobin\n\
    server $studentid-web-01 54.197.131.36 check\n\
    server $studentid-web-02 100.26.226.35 check\n\
    " | sudo tee -a /etc/haproxy/haproxy.cfg
