#!/usr/bin/env bash
# listening on port 80 of all server's active ipv4 ips
rm -rf /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo systemctl start nginx
