#!/usr/bin/env bash
# listening on port 80 of all server's active ipv4 ips
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start