#!/usr/bin/env bash
#fizzbuzzz
for i in {1..100}; do
    if ((i % 15 == 0)); then
        echo "FizzBuzz"
    fi
    if ((i % 3 == 0)); then
        echo "Fizz"
    fi
    if ((i % 5 == 0)); then
        echo "Buzz"
    fi
    echo $i
done