#!/usr/bin/env bash
#this uses while loop to print best school 10 times on the 9th iteration print
count=0
while [ $count -lt 10 ]; do
    echo "Best School"
    if [ $count -eq 8 ]; then
        echo "Hi"
    fi
    ((count++))
    
done