#!/usr/bin/env bash
#this uses while loop to print best school 10 times on the 9th iteration print
count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 3 ]; then
        echo "bad luck"
    elif [ $count -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done