#!/usr/bin/env bash
#checks if file exists
school="/home/vboxuser/Documents/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"
if [ -f "$school" ]; then
    echo "school exists"
    
    if [ -s "$school" ]; then
        echo "school file is not empty"
    fi
    if [ ! -s "$school" ]; then
        echo "school file is empty"
    fi
    echo "school is a regular file"
else 
    echo "school file does not exist"
fi
