#!/usr/bin/env bash
#change your home ip
newlocalhostip="127.0.0.2"
newfacebookip="8.8.8.8"
hostfile="/etc/hosts"
backup="$HOME/hosts.new"
sudo cp $hostfile "$backup"
sudo sed -i "s/127.0.0.1/$newlocalhostip/g" "$backup"
echo "$newfacebookip facebook.com" >> "$backup"
sudo cp -f "$backup" "$hostfile"