#!/usr/bin/env bash
#get apache to run on container and returning a page when quering to the root
sudo docker run -p 8080:80 -d --name my-apache-server httpd
sudo docker exec my-apache-server sh -c 'echo "Hello Holberton" > /usr/local/apache2/htdocs/index.html'
