#!/usr/bin/env bash
#get nginx to run as the user nginx
sudo useradd -r -s /bin/false nginx
echo "user nginx;" | sudo tee -a /etc/nginx/nginx.conf
echo "server {
	listen 8080;
}" | sudo tee /etc/nginx/sites-available/default
sudo nginx -t
sudo systemctl restart nginx

